name: CI

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0

  tests:
    strategy:
      fail-fast: false
      matrix:
        script:
          - name: Basic
            args: "--directory=profile_basic"
          - name: Abbreviations
            args: "--directory=profile_abbreviations"

    name: "${{ matrix.script.name }} profile tests"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: fish-actions/install-fish@v1.1.0
      - uses: Gr1N/setup-poetry@v8
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
      - name: Install dependencies
        run: poetry install
      - name: Basic tests for ${{ matrix.script.name }} profile
        run: poetry run fish tests/test_basic.fish ${{ matrix.script.args }}
      - name: Fisher tests for ${{ matrix.script.name }} profile
        run: poetry run fish tests/test_fisher.fish ${{ matrix.script.args }}
