name: CI

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0

  tests:
    strategy:
      fail-fast: false
      matrix:
        script:
          - name: Fisher basic
            args: "--directory=fisher_basic"
          - name: Fisher abbreviations
            args: "--directory=fisher_abbreviations"

    name: "${{ matrix.script.name }} plugin tests"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: fish-actions/install-fish@v1.1.0
      - name: Install Fisher plugin manager
        uses: fish-shop/install-plugin-manager@v1
        with:
          plugin-manager: fisher
      - name: Install fishtape
        uses: fish-shop/install-plugin@v1
        with:
          plugin-manager: fisher
          plugins: jorgebucaran/fishtape
      - uses: Gr1N/setup-poetry@v8
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
      - name: Install dependencies
        run: poetry install
      - name: Basic tests
        run: poetry run fish tests/test_basic.fish ${{ matrix.script.args }}
      - name: Fisher tests
        run: poetry run fish tests/test_fisher.fish ${{ matrix.script.args }}
